version: "3.9"
services:
 #NGINX
 nginx:
  build: ./server/nginx/
  ports:
  - 80:80  
  volumes:
  - './WebRoot/:/var/www/html/' 
  networks:
  - app-network
 
 #PHP
 php:
  build: ./server/php/
  expose:
  - 9000
  volumes:
  - './WebRoot/:/var/www/html/'
  networks:
  - app-network
 
 #MYSQL
 db:
 # build: ./db/
  image: mysql:8.0
  command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: coalize
   MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  ports:
  - '3306:3306'
  volumes:
  - './server/db/data:/var/lib/mysql'
  - './server/db/my.cnf:/etc/mysql/conf.d/my.cnf'
  - './server/db/sql:/docker-entrypoint-initdb.d'
  networks:
  - app-network

#NETWORKS
networks:
 app-network:
  driver: bridge

#VOLUMES
#volumes:
 # dbdata:
  #  driver: local


#docker-compose down && cls && docker-compose up -d --force-recreate --build php nginx db